baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = 'Upstanding Robot'
summaryLength = 1000

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[params]
  description = "Curated technical and design links"
  author = "Your Name"
  defaultImage = "/og-default.png"
  twitter = ""

[permalinks]
  posts = "/:year/:month/:day/:slug/"

[taxonomies]
  tag = "tags"
  category = "categories"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
